# Generated by Django 3.2.9 on 2021-12-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='komponen',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
