# Generated by Django 3.2.9 on 2021-12-05 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_komponen_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooler',
            name='komponen_ptr',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='komponen_ptr',
        ),
        migrations.RemoveField(
            model_name='disk',
            name='komponen_ptr',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='komponen_ptr',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='komponen_ptr',
        ),
        migrations.RemoveField(
            model_name='powersupply',
            name='komponen_ptr',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='komponen_ptr',
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='Cooler',
        ),
        migrations.DeleteModel(
            name='CPU',
        ),
        migrations.DeleteModel(
            name='Disk',
        ),
        migrations.DeleteModel(
            name='Fan',
        ),
        migrations.DeleteModel(
            name='Motherboard',
        ),
        migrations.DeleteModel(
            name='PowerSupply',
        ),
        migrations.DeleteModel(
            name='RAM',
        ),
    ]
